apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: one-key-balance-kit${env_suffix}
  labels:
    environment: ${environment}
  annotations:
    run.googleapis.com/client-name: 'github-actions'
    run.googleapis.com/ingress: 'all'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/maxScale: '${max_instances}'
        run.googleapis.com/cpu-throttling: 'true'
        run.googleapis.com/execution-environment: 'gen2'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
        - image: ${image_path}:${img_tag}
          resources:
            limits:
              cpu: '1'
              memory: '1Gi'
          env:
            - name: NODE_ENV
              value: ${node_env}
            - name: APP_NAME
              value: one-key-balance-kit${env_suffix}
            - name: LOG_LEVEL
              value: '${log_level}'
            - name: API_BASE_URL
              value: ${api_base_url}
            - name: CORS_ORIGIN
              value: '${cors_origin}'
            - name: WEBHOOK_URL
              value: ${webhook_url}
            - name: NETWORK_TIMEOUT
              value: '30000'
            - name: NETWORK_RETRIES
              value: '3'
            # -------- Secret references --------
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: ${secret_prefix}_MONGO_URL
                  key: latest
            - name: MONGO_HOST
              valueFrom:
                secretKeyRef:
                  name: ${secret_prefix}_MONGO_HOST
                  key: latest
            - name: MONGO_PORT
              valueFrom:
                secretKeyRef:
                  name: ${secret_prefix}_MONGO_PORT
                  key: latest
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ${secret_prefix}_MONGO_USERNAME
                  key: latest
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ${secret_prefix}_MONGO_PASSWORD
                  key: latest
            - name: MONGO_DATABASE
              valueFrom:
                secretKeyRef:
                  name: ${secret_prefix}_MONGO_DATABASE
                  key: latest
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: ${secret_prefix}_REDIS_HOST
                  key: latest
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: ${secret_prefix}_REDIS_PORT
                  key: latest
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ${secret_prefix}_REDIS_PASSWORD
                  key: latest
            - name: REDIS_DB
              valueFrom:
                secretKeyRef:
                  name: ${secret_prefix}_REDIS_DB
                  key: latest
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: ${secret_prefix}_REDIS_URL
                  key: latest
            - name: RPC_URL
              valueFrom:
                secretKeyRef:
                  name: ${secret_prefix}_RPC_URL
                  key: latest
            - name: CHAIN_ID
              valueFrom:
                secretKeyRef:
                  name: ${secret_prefix}_CHAIN_ID
                  key: latest
            - name: ALCHEMY_API_KEY_ETH
              valueFrom:
                secretKeyRef:
                  name: ${secret_prefix}_ALCHEMY_API_KEY_ETH
                  key: latest
            - name: ALCHEMY_API_KEY_SOL
              valueFrom:
                secretKeyRef:
                  name: ${secret_prefix}_ALCHEMY_API_KEY_SOL
                  key: latest
            - name: ALCHEMY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ${secret_prefix}_ALCHEMY_API_KEY
                  key: latest
            - name: ALCHEMY_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ${secret_prefix}_ALCHEMY_TOKEN
                  key: latest
            - name: QUICKNODE_ETH_MAINNET_URL
              valueFrom:
                secretKeyRef:
                  name: ${secret_prefix}_QUICKNODE_ETH_MAINNET_URL
                  key: latest
            - name: QUICKNODE_ETH_TESTNET_URL
              valueFrom:
                secretKeyRef:
                  name: ${secret_prefix}_QUICKNODE_ETH_TESTNET_URL
                  key: latest
            - name: OKX_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ${secret_prefix}_OKX_API_KEY
                  key: latest
            - name: OKX_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: ${secret_prefix}_OKX_SECRET_KEY
                  key: latest
            - name: OKX_API_PASSPHRASE
              valueFrom:
                secretKeyRef:
                  name: ${secret_prefix}_OKX_API_PASSPHRASE
                  key: latest
            - name: OKX_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: ${secret_prefix}_OKX_PROJECT_ID
                  key: latest
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: ${secret_prefix}_API_KEY
                  key: latest
          # ---- Health checks ----
          startupProbe:
            httpGet:
              path: /v1/api/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /v1/api/health
              port: 8080
            periodSeconds: 30
            failureThreshold: 3
  traffic:
    - percent: 100
      latestRevision: true
